Error: UPGRADE FAILED: cannot patch "hello-world-service-chart" with kind Deployment: Deployment.apps "hello-world-service-chart" is invalid: spec.template.spec.containers[0].volumeMounts[0].mountPath: Required value
Because I'm an idiot....